spring:
  application:
    name: competence-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: competence-service    # ID ?????? ??????? ? Keycloak
            client-secret: ymdrtdRWHF56mHqvoFjgXhw3h4PVUFaM   # ??? ?????????? ??????
            authorization-grant-type: client_credentials      # ??? grant - client credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/microservices-realm  # ????? ?????? Keycloak Realm
            token-uri: http://localhost:8080/realms/microservices-realm/protocol/openid-connect/token
            jwk-set-uri: http://localhost:8080/realms/microservices-realm/protocol/openid-connect/certs
#  jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/cv_db
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
   prefer-ip-address: true

# ????????? Feign ??? ????????? ?????????
feign:
  client:
    config:
      default:
        connectTimeout: 5000  # ??????? ??????????
        readTimeout: 5000     # ??????? ???????? ??????

#keycloak:
#  realm: microservices-realm  # ??? realm
#  auth-server-url: http://localhost:8080  # ????? Keycloak ???????
#  resource: competence-service  # Client ID, ??????? ?? ??????? ? Keycloak
#  credentials:
#    secret: ymdrtdRWHF56mHqvoFjgXhw3h4PVUFaM  # ??????, ??????? ?? ???????????
#  bearer-only: true  # ?????? ??? ?????????? API
