server:
  port: 8761

eureka:
  client:
    register-with-eureka: false   # Eureka ?????? ?? ?????? ??? ???????????????? ? ????
    fetch-registry: false         # ?? ?? ?????? ???????? ???????? ?????? ???????
  server:
    enable-self-preservation: false  # ????????? ?????????????? ??? ????????????
